[features]
seeds = false
skip-lint = false
[programs.localnet]
c5d3_movie_review = "59aXGszp71gKMND83XNfywpozaxVUJC1feyxFs227BYe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/eemcs/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
